name: Terraform Check

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [day1, day2, day3, day4]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ${{ matrix.dir }}
      run: terraform init

    - name: Terraform Format Check
      working-directory: ${{ matrix.dir }}
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: ${{ matrix.dir }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ matrix.dir }}
      run: terraform plan